<?php

	class ChatBlob { 
	
		var $Output = NULL, 
			$Title = NULL,
			$Body = NULL;
	
		function AddChatCmd( $Command, $LinkText = "Click Here" ) {
			$this->Body .= '<a href=\'chatcmd://' . $this->Clean($Command) . '\'>' . $LinkText . '</a>';			
		}
		
		function Clean( $Input ) {
			return $Input;
		}
		
		function ChatBlob( $Title = "Click Here" ) { 
		
			$this->Title = $Title;	
			$this->Body .= "<font color=" . COLOUR_HEADER . ">SellBot 1.0</font> <font color=" . COLOUR_HEADERL . ">Information Screen</font><br><br>"; // Append header
		
		}
		
		function AddText( $Text ) { $this->Body .= $Text; }

		function AddLineBreak() { $this->Body .= "<br>"; }
		
		function Render() { 
	
			global $Bot;
	
			$this->Body .= "<br><br><font color=" . COLOUR_FOOTER . ">Generated by SellBot</font> :: <a href='chatcmd:///tell " . $Bot->ShopCharacter . " About'>More Information</a>";
			$this->Output = '<a href="text://' . $this->Body . '">' . $this->Title . '</a>'; 
		}
	
	}
	
?>